name: test_flutter_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.4+6

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^5.8.0
  url_launcher: ^6.2.1
  flutter_sharing_intent: ^1.1.0
  supabase_flutter: ^2.1.0
  flutter_appauth: ^6.0.2
  crypto: ^3.0.3
  flutter_social_button: ^1.1.4+1
  uni_links: ^0.5.1
  flutter_hooks: ^0.20.3
  go_router: ^13.0.1
  material_design_icons_flutter: ^7.0.7296
  http: ^1.1.0
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  nil: ^1.1.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo.svg
    - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true